// <auto-generated />
using System;
using EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Migrations
{
    [DbContext(typeof(RajoDbContext))]
    [Migration("20260415115032_AddedJoke")]
    partial class AddedJoke
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Finnish_Swedish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Uddevalla",
                            CountryId = 1,
                            Street = "Äskebacka",
                            StreetNumber = "125",
                            ZipCode = "451 95"
                        },
                        new
                        {
                            Id = 2,
                            City = "Uddevalla",
                            CountryId = 1,
                            Street = "Helenedalsvägen",
                            StreetNumber = "16",
                            ZipCode = "451 45"
                        },
                        new
                        {
                            Id = 3,
                            City = "Uddevalla",
                            CountryId = 1,
                            Street = "Kunsgatan",
                            StreetNumber = "22",
                            ZipCode = "451 30"
                        },
                        new
                        {
                            Id = 4,
                            City = "Lidköping",
                            CountryId = 1,
                            Street = "Stenhammarsvägen",
                            StreetNumber = "61",
                            ZipCode = "531 56"
                        });
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Öl"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sprit"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cider"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HB"
                        });
                });

            modelBuilder.Entity("Entities.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactTypeId = 1,
                            UserId = 5,
                            Value = "0743905120"
                        },
                        new
                        {
                            Id = 2,
                            ContactTypeId = 2,
                            UserId = 5,
                            Value = "eliassmmy76@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            ContactTypeId = 1,
                            UserId = 4,
                            Value = "0765968445"
                        },
                        new
                        {
                            Id = 4,
                            ContactTypeId = 2,
                            UserId = 4,
                            Value = "arosater@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            ContactTypeId = 1,
                            UserId = 3,
                            Value = "0713159305"
                        },
                        new
                        {
                            Id = 6,
                            ContactTypeId = 2,
                            UserId = 3,
                            Value = "ruhollahkari@gmail.com"
                        },
                        new
                        {
                            Id = 7,
                            ContactTypeId = 1,
                            UserId = 2,
                            Value = "0123414142"
                        },
                        new
                        {
                            Id = 8,
                            ContactTypeId = 2,
                            UserId = 2,
                            Value = "olle@olle.se"
                        });
                });

            modelBuilder.Entity("Entities.Models.ContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ContactTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Telefonnummer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Epost"
                        });
                });

            modelBuilder.Entity("Entities.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sverige"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tjeckien"
                        },
                        new
                        {
                            Id = 3,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tyskland"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Italien"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Frankrike"
                        });
                });

            modelBuilder.Entity("Entities.Models.Joke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Jokes");
                });

            modelBuilder.Entity("Entities.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Spendrups"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Carlsberg Sverige"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "Pilsner Urquell"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Budvar"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Budweiser"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            Name = "Coors"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 4,
                            Name = "Paulaner"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 4,
                            Name = "Becks"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 5,
                            Name = "Peroni"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 5,
                            Name = "Moretti"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 6,
                            Name = "Kronenbourg"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 6,
                            Name = "1664 Blanc"
                        });
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentAlternativeId")
                        .HasColumnType("int");

                    b.Property<int>("ShippingAlternativeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("PaymentAlternativeId");

                    b.HasIndex("ShippingAlternativeId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 2,
                            PaymentAlternativeId = 2,
                            ShippingAlternativeId = 1,
                            Status = "Mottagen",
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 4,
                            PaymentAlternativeId = 1,
                            ShippingAlternativeId = 2,
                            Status = "Mottagen",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            PaymentAlternativeId = 2,
                            ShippingAlternativeId = 1,
                            Status = "Mottagen",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1,
                            PaymentAlternativeId = 1,
                            ShippingAlternativeId = 2,
                            Status = "Mottagen",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Entities.Models.OrderRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderRows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 6,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 14,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 7,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 11,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 9,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 15,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("Entities.Models.PaymentAlternative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("PaymentAlternatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fee = 29.00m,
                            Name = "Faktura"
                        },
                        new
                        {
                            Id = 2,
                            Fee = 0.00m,
                            Name = "Kortbetalning"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Showcase")
                        .HasColumnType("bit");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Svensk ljus lager.",
                            ManufacturerId = 1,
                            Name = "Spendrups Bright Lager",
                            Price = 22m,
                            Showcase = true,
                            Stock = 15,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Klassisk exportlager.",
                            ManufacturerId = 2,
                            Name = "Carlsberg Export",
                            Price = 23m,
                            Showcase = false,
                            Stock = 18,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Tjeckisk pilsner.",
                            ManufacturerId = 3,
                            Name = "Pilsner Urquell Original",
                            Price = 26m,
                            Showcase = true,
                            Stock = 16,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Maltig lager.",
                            ManufacturerId = 4,
                            Name = "Budvar Original",
                            Price = 25m,
                            Showcase = false,
                            Stock = 14,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Amerikansk lager.",
                            ManufacturerId = 5,
                            Name = "Budweiser Lager",
                            Price = 22m,
                            Showcase = false,
                            Stock = 20,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Tysk veteöl.",
                            ManufacturerId = 7,
                            Name = "Paulaner Weissbier",
                            Price = 28m,
                            Showcase = true,
                            Stock = 12,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Italienskt rödvin.",
                            ManufacturerId = 9,
                            Name = "Chianti Classico",
                            Price = 119m,
                            Showcase = false,
                            Stock = 10,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Friskt vitt vin.",
                            ManufacturerId = 10,
                            Name = "Pinot Grigio",
                            Price = 99m,
                            Showcase = false,
                            Stock = 11,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Franskt kvalitetsvin.",
                            ManufacturerId = 11,
                            Name = "Bordeaux Rouge",
                            Price = 149m,
                            Showcase = false,
                            Stock = 8,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Ren vodka.",
                            ManufacturerId = 1,
                            Name = "Vodka Premium",
                            Price = 249m,
                            Showcase = false,
                            Stock = 7,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Lagrad whiskey.",
                            ManufacturerId = 5,
                            Name = "Whiskey Reserve",
                            Price = 329m,
                            Showcase = false,
                            Stock = 5,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Päroncider.",
                            ManufacturerId = 2,
                            Name = "Somersby Pear",
                            Price = 24m,
                            Showcase = false,
                            Stock = 18,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Torr äppelcider.",
                            ManufacturerId = 6,
                            Name = "Apple Dry Cider",
                            Price = 26m,
                            Showcase = false,
                            Stock = 14,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Hemblandad specialdryck.",
                            ManufacturerId = 1,
                            Name = "HB Stark Special",
                            Price = 189m,
                            Showcase = false,
                            Stock = 3,
                            VatRate = 0.25m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Traditionell HB.",
                            ManufacturerId = 3,
                            Name = "HB Classic",
                            Price = 169m,
                            Showcase = false,
                            Stock = 4,
                            VatRate = 0.25m
                        });
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Entities.Models.ShippingAlternative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ShippingAlternatives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DHL",
                            Price = 49.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "PostNord",
                            Price = 89.00m
                        });
                });

            modelBuilder.Entity("Entities.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jimmys kundvagn",
                            UserId = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Arons kundvagn",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ruhollahs kundvagn",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Olles kundvagn",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Entities.Models.ShoppingCartRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartRows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 2,
                            Quantity = 3,
                            ShoppingCartId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 4,
                            Quantity = 2,
                            ShoppingCartId = 1
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 5,
                            ShoppingCartId = 2
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 12,
                            Quantity = 2,
                            ShoppingCartId = 2
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 11,
                            Quantity = 2,
                            ShoppingCartId = 3
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 14,
                            Quantity = 4,
                            ShoppingCartId = 3
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 3,
                            ShoppingCartId = 4
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 9,
                            Quantity = 5,
                            ShoppingCartId = 4
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            RoleId = 2,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Olle",
                            RoleId = 1,
                            UserName = "olle"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ruhollah",
                            RoleId = 1,
                            UserName = "ruhollah"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aron",
                            RoleId = 1,
                            UserName = "aron"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jimmy",
                            RoleId = 1,
                            UserName = "jimmy"
                        });
                });

            modelBuilder.Entity("Entities.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.HasOne("Entities.Models.Country", "Country")
                        .WithMany("Addresses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Entities.Models.ContactInfo", b =>
                {
                    b.HasOne("Entities.Models.ContactType", "ContactType")
                        .WithMany("ContactInfos")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("ContactInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Manufacturer", b =>
                {
                    b.HasOne("Entities.Models.Country", "Country")
                        .WithMany("Manufacturers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.HasOne("Entities.Models.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.PaymentAlternative", "PaymentAlternative")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentAlternativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.ShippingAlternative", "ShippingAlternative")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAlternativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("PaymentAlternative");

                    b.Navigation("ShippingAlternative");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.OrderRow", b =>
                {
                    b.HasOne("Entities.Models.Order", "Order")
                        .WithMany("OrderRows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("OrderRows")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Entities.Models.ShoppingCart", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.ShoppingCartRow", b =>
                {
                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("ShoppingCartRows")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartRows")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.HasOne("Entities.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entities.Models.UserAddress", b =>
                {
                    b.HasOne("Entities.Models.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Address", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.ContactType", b =>
                {
                    b.Navigation("ContactInfos");
                });

            modelBuilder.Entity("Entities.Models.Country", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Manufacturers");
                });

            modelBuilder.Entity("Entities.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Navigation("OrderRows");
                });

            modelBuilder.Entity("Entities.Models.PaymentAlternative", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Navigation("OrderRows");

                    b.Navigation("ShoppingCartRows");
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.Models.ShippingAlternative", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Models.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartRows");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("ContactInfos");

                    b.Navigation("Orders");

                    b.Navigation("ShoppingCarts");

                    b.Navigation("UserAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
